export const mockDataAddressLookup = {
  validPostcode: 'NW19TL',
  data: {
    addresses: [
      {
        mpan: 'i2T5qz4VMe07%2b%2bEbYZJq1bNcAApB0Sw61ebXy5JiahtVUIpL6tM8U%2bmxjpbYIDhvW1AiMpHtclOY8PZD7xiRrRpKT97KmZG9DfSF1UoT7IwgBNVX%2bPFNvrXoyClBYKZx',
        uprn: 0,
        proNumber: 0,
        houseNo: 'FLAT 3',
        houseName: '9',
        streetName: 'QUEENSLAND ROAD',
        county: 'ISLINGTON',
        country: '',
        postCode: 'N77FH',
        dno: 15,
        supplierName: 'E.ON',
        supplierNumber: '08085015200',
        isInUkpnDno: false,
      },
      {
        mpan: 'xepBDE%2b2aF12%2bC0HRCFGv0DSeOse%2bgFsJtl2J1Wif4WHrge1esydxxh2%2blhUkhes%2bvn3RAyE3HQcdTgEvQyiI2oV3bls8woauVNSow%2fH3w%2fD7msmkw1cwWYfNTaANdA3',
        uprn: 0,
        proNumber: 0,
        houseNo: '80',
        houseName: '',
        streetName: 'AGAR GROVE',
        county: 'LONDON',
        country: '',
        postCode: 'NW19TL',
        dno: 2,
        supplierName: 'EDF Energy',
        supplierNumber: '03332005100',
        isInUkpnDno: true,
      },
      {
        mpan: '7d%2bpHTfzkSePrTrGkAc9EbhtWZXFN2%2b64Q8QMDu5wog9vBDc%2fhCgFlrOUM3%2fsOicpTEYXHGvzS2CQUn4%2fjg%2b3OOEKJMz6wFDvkDGORpS8PADwD9AFFbISPkm%2fpNcR9Aq',
        uprn: 0,
        proNumber: 0,
        houseNo: 'FIFTH FLOOR',
        houseName: '16',
        streetName: 'LITTLE PORTLAND STREET',
        county: 'LONDON',
        country: '',
        postCode: 'W1W8BP',
        dno: 2,
        supplierName: 'E.ON',
        supplierNumber: '08085015699',
        isInUkpnDno: true,
      },
      {
        mpan: 'azD7FNlhbKyuUx7jFPBLqvyvr%2brQYhTL92VtoSMoOqcCu1nbeZ4TYZKF9%2fTWFkUsHiYfebpA%2f%2bmR0sOvFctSS7vYM6Pg6MDrBSOfXUanO%2bgFLJX6TbLZdszWK3Heha08',
        uprn: 0,
        proNumber: 0,
        houseNo: 'FLAT 3',
        houseName: '9',
        streetName: 'QUEENSLAND ROAD',
        county: 'ISLINGTON',
        country: '',
        postCode: 'N77FH',
        dno: 15,
        supplierName: 'E.ON',
        supplierNumber: '08085015200',
        isInUkpnDno: false,
      },
      {
        mpan: 'zTqqBOzrrBAA%2bzQWgoraFVsHuKmtf9YD%2fu5qJ5xCnOEFYLGWvsqbBYV672Ggc8cno5Y1eudmRklPVM%2b0AunUYkRGcwev8BxA1RXBlhIspdtazBOu399J2vnY6x3Ks2TF',
        uprn: 0,
        proNumber: 0,
        houseNo: '76',
        houseName: '',
        streetName: 'AGAR GROVE',
        county: 'LONDON',
        country: '',
        postCode: 'NW19TL',
        dno: 2,
        supplierName: 'British Gas',
        supplierNumber: '03332029802',
        isInUkpnDno: true,
      },
    ],
  },
}
