import { NewsArticle } from '_types/CMS/pages/main-site-pages'
import { PageTypeNames } from '_types/CMS'

export const mockNewsAndViewsData: NewsArticle[] = [
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
  {
    breadcrumb: 'breadcrumb',
    ancestors: {
      items: [],
    },
    name: 'Volunteers sow seeds for Uckfield’s new community garden',
    pageTitle: 'Volunteers sow seeds for Uckfield’s new community garden',
    subhead:
      'Plans to create a new community garden space in the heart of Uckfield are taking shape, helped by a team of electricity workers and colleagues from a local funeral directors.',
    __typename: PageTypeNames.NEWS_ARTICLE,
    publishedDate: '2022-02-09T00:00:00Z',
    desktopImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    tabletImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    mobileImage: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    image: {
      url: 'https://media.umbraco.io/dev-uk-power-networks/dcpmhmsm/solar-panels-at-home-1.jpg',
      name: 'Solar Panels At Home (1)',
      umbracoWidth: '1386',
      umbracoHeight: '936',
    },
    video: 'https://www.youtube.com/watch?v=GPeUnB6kvSY',
    contentTypeAlias: '',
    pageSubtitle: '',
    url: '/',
    id: '',
  },
]
